// Type declarations for @itslil/lil2-react-markdown. Generated by lilscript-work/lil2/release/types.mjs.
import type {ReactElement} from 'react'
import type {KatexOptions} from 'katex'
import type {Plugin} from './index.js'
import type {GfmOptions} from './gfm.js'
export * from './gfm.js'

/** The core props plus remark-gfm's, remark-math's and rehype-katex's. */
export interface FullOptions extends GfmOptions {
  /** remark-math's `singleDollarTextMath`: allow `$x$` text math (default true). */
  singleDollarTextMath?: boolean | null
  /** rehype-katex's options: KaTeX's (`displayMode` and `throwOnError` are set per formula). */
  katex?: KatexOptions | null
}

/** Renders markdown as React elements; `plugins={[GFM, MATH, KATEX, BREAKS]}` applies any of the four. */
export declare function Markdown(options: Readonly<FullOptions>): ReactElement
/** remark-math. */
export declare const MATH: Plugin
/** rehype-katex (KaTeX itself is the `katex` package). */
export declare const KATEX: Plugin
/** remark-breaks. */
export declare const BREAKS: Plugin
