// Type declarations for @itslil/lil2-react-markdown. Generated by lilscript-work/lil2/release/types.mjs.
import type {ReactElement} from 'react'
import type {Options, Plugin} from './index.js'
export * from './index.js'

/** The core props plus remark-gfm's. */
export interface GfmOptions extends Options {
  /** remark-gfm's `singleTilde`: allow `~one~` strikethrough (default true). */
  singleTilde?: boolean | null
}

/** Renders markdown as React elements; `plugins={[GFM]}` applies remark-gfm. */
export declare function Markdown(options: Readonly<GfmOptions>): ReactElement
/** remark-gfm. */
export declare const GFM: Plugin
