// Type declarations for @itslil/lil2-react-markdown. Generated by lilscript-work/lil2/release/types.mjs.
import type {ElementType, ReactElement, ReactNode} from 'react'

/**
 * The hast of one render as positional columns, shared by every element of that render.
 *
 * A node's kind is `kind[node]`, one of the `H_*` constants (`/constants`); an element's tag
 * name is `tagNames[tag[node]]` and text, comment and raw nodes keep their text in `value`. Children run from
 * `firstChild[node]` along `nextSibling`; -1 ends the list and means "none" in every link column. An element's
 * properties run from `propHead[node]` along `propNext`: each has a name (`propNames[propName[p]]`), a kind
 * (`P_*`: string, number, boolean, list, keyword or float) and its value in `propString` (string and list
 * values; a list is space separated) or `propNumber` (numbers, booleans as 0/1, and `P_KEYWORD` ids into
 * `keywordNames`). Positions are offsets into the source; `lineStarts` turns an offset into a line and column.
 */
export type HastTree = readonly [
  kind: readonly number[],
  parent: readonly number[],
  firstChild: readonly number[],
  nextSibling: readonly number[],
  tag: readonly number[],
  value: readonly string[],
  startOffset: readonly number[],
  endOffset: readonly number[],
  flags: readonly number[],
  meta: readonly string[],
  propHead: readonly number[],
  propName: readonly number[],
  propKind: readonly number[],
  propString: readonly string[],
  propNumber: readonly number[],
  propNext: readonly number[],
  lineStarts: readonly number[],
  tagNames: readonly string[],
]

declare const plugin: unique symbol
/** A plugin id, exported by the flavor that compiles the plugin in (`/gfm`, `/full`). */
export type Plugin = number & {readonly [plugin]: true}

/** What every custom component gets besides the element's own properties. */
export interface ExtraProps {
  /** The element's node id in `tree`. */
  node: number
  /** The hast columns of this render, shared by every element. */
  tree: HastTree
}

/** A component that renders one tag: it gets the element's properties (`className`, `href`, …), `children`,
 * `node` and `tree`. */
export type MarkdownComponent = ElementType<{[property: string]: any} & ExtraProps & {children?: ReactNode}>

/** `[TAG_H1, Title, TAG_A, Link, …]`: tag id and component pairs (react-markdown's `components` object), up to
 * 40 pairs. */
export type Components =
  | readonly []
  | readonly [number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]
  | readonly [number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent, number, MarkdownComponent]

/** Decides whether to keep an element (react-markdown's `allowElement`), with ids into `tree`. */
export type AllowElement = (node: number, index: number, parent: number, tree: HastTree) => boolean | null | undefined

/** Rewrites a URL (react-markdown's `urlTransform`): `key` is a `PROP_*` id (`PROP_HREF`, `PROP_SRC`). */
export type UrlTransform = (url: string, key: number, node: number, tree: HastTree) => string | null | undefined

/** A footnote back reference's label or content: a string, or a function of the reference's and rereference's index. */
export type FootnoteBack = string | ((referenceIndex: number, rereferenceIndex: number) => string)

/** react-markdown 10's props, with tag and property ids instead of names and plugin ids instead of plugins. */
export interface Options {
  /** Markdown. Anything else renders nothing, as upstream's production build. */
  children?: string | null
  /** Plugin ids applied in upstream's order (remark plugins, then rehype plugins): `[GFM, MATH, KATEX, BREAKS]`. */
  plugins?: readonly Plugin[] | null
  /** Tag id and component pairs. */
  components?: Components | null
  /** Tag ids to keep; the others are removed (or unwrapped). Wins over `disallowedElements`. */
  allowedElements?: readonly number[] | null
  /** Tag ids to remove (or unwrap). */
  disallowedElements?: readonly number[] | null
  allowElement?: AllowElement | null
  /** Replace removed elements with their children. */
  unwrapDisallowed?: boolean | null
  /** Ignore HTML in markdown. */
  skipHtml?: boolean | null
  /** Default: `defaultUrlTransform`. */
  urlTransform?: UrlTransform | null
  /** remark-rehype's footnote options. */
  clobberPrefix?: string | null
  footnoteLabel?: string | null
  /** A tag id. */
  footnoteLabelTag?: number | null
  footnoteBackLabel?: FootnoteBack | null
  footnoteBackContent?: FootnoteBack | null
}

/** Renders markdown as React elements: react-markdown's `<Markdown>`. */
export declare function Markdown(options: Readonly<Options>): ReactElement
/** Makes a URL safe: react-markdown's `defaultUrlTransform`. */
export declare function defaultUrlTransform(value: string): string
